a.out : main.o display.o add_list.o reverse.o
	cc main.o display.o add_list.o reverse.o
main.o : main.c
	cc -c main.c
display.o : display.c
	cc -c display.c
add_list.o : add_list.c
	cc -c add_list.c
reverse.o : reverse.c
	cc -c reverse.c
