a.out : main.o add_first.o dlte_data.o display.o
	cc main.o add_first.o dlte_data.o display.o

main.o : main.c
	cc -c main.c
add_first.o : add_first.c
	cc -c add_first.c
display.o : display.c
	cc -c display.c
dlte_data.o : dlte_data.c
	cc -c dlte_data.c
