a.out : add_list.o main.o display.o nth_node.o 
	cc add_list.o main.o display.o nth_node.o
add_list.o : add_list.c
	cc -c add_list.c
main.o : main.c
	cc -c main.c
dipaly.o : display.c
	cc -c display.c
display_prime.o : nth_node.c
	cc -c nth_node.c


