a.out : main.o add_last.o display.o del_first.o
	cc main.o add_last.o display.o del_first.o
main.o : main.c
	cc -c main.c
add_last.o : add_last.c
	cc -c add_last.c
display.o : display.c
	cc -c display.c
del_last.o : del_first.c
	cc -c del_first.c
