a.out : add_list.o display.o main.o count.o
	cc add_list.o display.o main.o count.o
add_list.o : add_list.c
	cc -c add_list.c
display.o : display.c
	cc -c display.c
main.o : main.c
	cc -c main.c
count.o : count.c
	cc -c count.c
