a.out : main.o insert.o preorder.o postorder.o inorder.o
	cc main.o insert.o preorder.o postorder.o inorder.o
main.o : main.c 
	cc -c main.c
insert.o : insert.c
	cc -c insert.c
preorder.o : preorder.c
	cc -c preorder.c
postorder.o : postorder.c
	cc -c postorder.c
inorder.o : inorder.c
	cc -c inorder.c	
