a.out : main.o add_first.o display.o dlte_first.o
	cc main.o add_first.o display.o dlte_first.o
main.o : main.c
	cc -c main.c
add_first.o : add_first.c
	cc -c add_first.c
display.o : display.c
	cc -c display.c
dlte_first.o : dlte_first.c
	cc -c dlte_first.c
