a.out : add_list.o main.o display.o print_node_reverse.o 
	cc add_list.o main.o display.o print_node_reverse.o
add_list.o : add_list.c
	cc -c add_list.c
main.o : main.c
	cc -c main.c
dipaly.o : display.c
	cc -c display.c
display_prime.o : print_node_reverse.c
	cc -c print_node_reverse.c


