a.out: main.o add_last.o display.o dlte.o
	cc main.o add_last.o display.o dlte.o
main.o : main.c
	cc -c main.c
display.o : display.c
	cc -c display.c
add_last.o : add_last.c
	cc -c add_last.c
dlte.o : dlte.c
	cc -c dlte.c
