a.out : main.o add_first.o del_first.o display.o
	cc main.o add_first.o del_first.o display.o
main.o : main.c
	cc -c main.c
add_first.o : add_first.c
	cc -c add_first.c
display.o : display.c
	cc -c display.c
del_first.o : del_first.c
	cc -c del_first.c
