a.out : main.o push.o pop.o peek.o display.o 
	cc main.o push.o pop.o peek.o display.o
main.o : main.c
	cc -c main.c
push.o : push.c
	cc -c push.c
display.o : display.c
	cc -c display.c
pop.o : pop.c
	cc -c pop.c
peek.o : peek.c
	cc -c peek.c
