a.out : main.o insert.o min.o delete.o inorder.o
	cc main.o insert.o min.o delete.o inorder.o
main.o : main.c 
	cc -c main.c
insert.o : insert.c
	cc -c insert.c
min.o : min.c
	cc -c min.c
delete.o : delete.c
	cc -c delete.c
inorder.o : inorder.c
	cc -c inorder.c

