a.out: queue_main.o addQueue.o rmQueue.o displayQueue.o exitFun.o
	cc queue_main.o addQueue.o rmQueue.o displayQueue.o exitFun.o 

addQueue.o: addQueue.c
	cc -c addQueue.c

rmQueue.o: rmQueue.c
	cc -c rmQueue.c

displayQueue.o: displayQueue.c 
	cc -c displayQueue.c

exitFun.o: exitFun.c 
	cc -c exitFun.c 