a.out : add_list.o main.o display.o display_prime.o 
	cc add_list.o main.o display.o display_prime.o
add_list.o : add_list.c
	cc -c add_list.c
main.o : main.c
	cc -c main.c
dipaly.o : display.c
	cc -c display.c
display_prime.o : display_prime.c
	cc -c display_prime.c

