a.out : main.o add_last.o display.o reverse.o
	cc main.o add_last.o display.o reverse.o
main.o : main.c
	cc -c main.c
add_last.o : add_last.c
	cc -c add_last.c
display.o : display.c
	cc -c display.c
reverse.o : reverse.c
	cc -c reverse.c
