a.out : main.o add_first.o display.o delete_data.o 
	cc main.o add_first.o display.o delete_data.o
main.o : main.c
	cc -c main.c
add_first.o : add_first.c
	cc -c add_first.c
display.o : display.c
	cc -c display.c
delete_data.o : delete_data.c
	cc -c delete_data.c


