a.out : main.o display.o add_last.o  del_data.o 
	cc main.o display.o add_last.o del_data.o
main.o : main.c
	cc -c main.c
display.o : display.c
	cc -c display.c
add_last.o : add_last.c
	cc -c add_last.c
del_data.o : del_data.c
	cc -c del_data.c

