a.out : main.o insert.o inorder.o min.o max.o 
	cc main.o insert.o inorder.o min.o max.o
main.o : main.c 
	cc -c main.c
insert.o : insert.c
	cc -c insert.c
min.o : min.c
	cc -c min.c
max.o : max.c
	cc -c max.c
inorder.o : inorder.c
	cc -c inorder.c


