a.out : main.o setArray.o getArray.o bubbleSort.o randomNoGen.o
		cc main.o setArray.o getArray.o bubbleSort.o randomNoGen.o
main.o : main.c 
	cc -c main.c
setArray.o : setArray.c 
	cc -c setArray.c 
getArray.o : getArray.c
	cc -c getArray.c
bubbleSort.o : bubbleSort.c
	cc -c bubbleSort.c
randomNoGen.o : randomNoGen.c
	cc -c randomNoGen.c