a.out : main.o display.o add_last.o middle.o 
	cc main.o display.o add_last.o middle.o
main.o : main.c
	cc -c main.c
display.o : display.c
	cc -c display.c
add_last.o : add_last.c
	cc -c add_last.c
middle.o : middle.c
	cc -c middle.c
